### ISSUE TITLE
Please have Network Admin options like regular Buddypress

### ISSUE THREAD

**Issue by rhisss** [buddydev/mediapress#1]
It should be available as a Network Plugin just like Buddypress, so that in WP Multisite-BP environment its settings can be saved centrally
for example its admin url should be like wp-admin/network/settings.php?page=mediapress

Since this is "Network Activated" with no settings options there, users in such a network can create Gallery but when they try to upload pictures the pictures are not uploaded, instead an error message is shown. Unless the end-user manually configures the settings (which he is not aware he has to do) pictures cannot be saved

Having two interfaces - the WP dasboard interface and again Buddypress interface is confusing for the end-user - can there be any sync between the two?

**Comment by sbrajesh** [comment]
Hi,
I think this is more of a communication issue than a bug. At the moment, You only need to enable the MediaPress plugin on the main site( or the sub site where BuddyPress is active).

MediaPress supports Multisite install of BuddyPress but It does not support the MultiBlog mode of BuddyPress. I am going to add that soon too.

For now, Just to clarify, activate it on your main site and update the settings. End user's won't need to do anything. They will be able to create gallery/upload photos etc as normal.

**Comment by rhisss** [comment]
<b>At present, testing with the latest Mediapress beta, in the  scenario below, end-users always get error message and cannot upload images even if they have individually saved the settings</b>

Install WP 4.1 and install BP 2.1.1 - fresh installs, nothing else
Enable WP multisite - define('MULTISITE', true); define('SUBDOMAIN_INSTALL', false); etc etc
Enable Mediapress, SAVE settings - all checked, Saved
Go to wp-admin/network/site-new.php and create a new site - a new user is created automatically by wordpress if   email address was not in the database
Now edit end-user password etc ( and send email to him with password etc)
Login as that end-user and try to create gallery, upload an image
You can cretae gallery as an end-user but when you try to upload image
You will get an error-message "xyz.jpg(xyz kb) x This file type is not allowed in current gallery. Only files are allowed!"
This error message is because the end-user has not visited wordpress/end-ser-site/wp-admin/edit.php?post_type=mpp-gallery&page=mpp-settings and checked "Enabled Media/gallery types" etc
This settings were indeed checked and saved in the main site by the site admin BUT this has not been reflected/saved for new sites and new end-users. Ideally end-user should not be able to see Plugin name and settings in his dashboard as site-wide plugin administration stands disabled already by the site super-admin

I suggest the following
![untitled3](https://cloud.githubusercontent.com/assets/3778500/5750746/f51a19a8-9c7e-11e4-8e7b-95b6740da14d.PNG)

At present, testing with the latest Mediapress beta, in the above scenario, end-users always get error message and cannot upload images even if they have individually saved the settings

**Comment by sbrajesh** [comment]
This was an elusive issue and finally fixed it after Andy's post on our forum. 
In multisite, when a user is not member of the site where MediaPress is active, They don't have 'read' capability. So, when we created gallery, they were not getting assigned status/type( terms). 

Fixed in
685143e6a0581e6e6d931cec08a4305847b8a92e
