### ISSUE TITLE
Users cannot upload photos in their own sites

### ISSUE THREAD

**Issue by dranii** [buddydev/mediapress#10]
Hi, I have been trying the latest github version of Mediapress with WP 4.1 and BP 2.2

I have the following settings:
 Both sites and user accounts can be registered.
 define('MULTISITE', true);
 define('SUBDOMAIN_INSTALL', false);

The site super admin can upload photos.
But people who register, and have both accounts and sites, can create gallery but cannot upload photos.
They get the error message "This file type is not allowed in current gallery. Only files are allowed!"
The created Gallery does not show up later that is, it is not saved.
Same thing happens for them from dashboard/backend and frontend.

I have tried not to Network-Activate Mediapress but activate it from the individual user's dashboard.
But things do not work. That is to say, users cannot see "Create Gallery" etc. When the Network-Activation is done they can see  "Create Gallery" and can create gallery but cannot upload pictures as described above.

Same results with previous version, latest github master, infact all available versions of Mediapress.
Using the same settings, Modemloopers Buddypics and Rtmedia free version works without any problem.

**Comment by sbrajesh** [comment]
This has been fixed. I am sorry I could not keep a track of initial tickets and could not reply back. 

MediaPress is tested with Multisite now and will work. Closing this ticket due to its age. If anyone having similar issue, please open a ticket or use our community forums. We will be happy to assist.
