### ISSUE TITLE
Several warning and notice

### ISSUE THREAD

**Issue by danbp** [buddydev/mediapress#13]
Hi Brajesh,

i'm very concerned by MediaPress, as an interesting enhancement of BuddyPress. I'm not a delopper, so i won't tell to much about your work, at least for now. That said, the demo site using BP Default and _only_ a single install, is a bit reducing the magic of possibilities and avaible improvements introduced since BP 2.x

If you allow me a suggestion, take a look at BuddyDrive and Rendez-Vous plugins, as examplary coding for specific BP plugins. There is also a project by Mark Jaquith, which could be interesting to check. https://github.com/markjaquith/Showdown

Concerning my issue
network multisite local,
WP 4.1
BP 2.2
PHP 5.5.12
Apache 2.4.9
Twenty Thirteen

**Issue description**

_When loged out_
Strict standards: Declaration of MPP_Group_Gallery_Extension::display() should be compatible with BP_Group_Extension::display($group_id = NULL) in ..\mediapress\modules\groups\group-extension.php on line 4

_When login_
Additionally to the above, 2 warnings related to
Warning: Cannot modify header information - headers already sent by (output started at C:\wamp\www\buddy\wp-content\plugins\mediapress\modules\groups\group-extension.php:4) in ..\wp-login.php on line 424 and 437

I'm running MediaPress live on bp-fr.net
If interested, i can give you access to his dev environment(MS), just let me know. PM me on the live site.

**Comment by sbrajesh** [comment]
Hi Dan,
Thank you.

Please allow me today to look at the multisite installation. I understand the issues you have mentioned. I will be updating the plugin and will get back to you again later today.

I appreciate your help, will certainly need your help in testing the updates :)

**Comment by danbp** [comment]
Hi Brajesh,
glad to (try) help out !

Please send me your email. (you can join me on http://bp-fr.net

Cheers !

**Comment by sbrajesh** [comment]
Hi Dan,
I am sorry I was not able to update earlier. 
I have fixed it in the trunk. Can you please upgrade and test? I am on PHP 5.3 and not on 5.4 so if you notice an issue, please do let me know.

**Comment by sbrajesh** [comment]
Fixed in 0d349593776ada

**Comment by danbp** [comment]
Please PM me on http://bp-fr.net so i can give you access to my dev site (MS)

MS local

Bugs
Except pictures, other medias aren't listed and don't show up

While deleting a gallery:
Notice: Trying to get property of non-object in mediapress\core\gallery\actions.php on line 591

Warning: Cannot modify header information - headers already sent by (output started at mediapress\core\gallery\actions.php:591) in wp-includes\pluggable.php on line 1178

**Comment by sbrajesh** [comment]
Hi Dan,
My apologies for not following properly. We fixed these in around 2-3 months ago. Just updating the ticket.

**Comment by sbrajesh** [comment]
Fixed all. Closing this
