### ISSUE TITLE
If Enable Gallery is unchecked, upload buttons still appear and media can still be uploaded

### ISSUE THREAD

**Issue by jazzsequence** [buddydev/mediapress#15]
If this setting is left unchecked in the group the upload buttons still appear:

![image](https://cloud.githubusercontent.com/assets/991511/6712973/386ccc94-cd55-11e4-9c09-a4ff13095ea5.png)

This means that when you click on the image when it posts to the group wall (which it will), the link will give a 404 error because the gallery is not enabled. 

There should be a check against that setting in this function: https://github.com/buddydev/mediapress/blob/master/core/activity/template.php#L5-L43

If the setting is not enabled, return and don't show the buttons.

**Comment by sbrajesh** [comment]
Hi Chris,
Just fixed it in 3cd56ee6234abe9bc6ace

Please do test and let me know if that fixes it or not?

**Comment by jazzsequence** [comment]
:+1: Looks good.

**Comment by sbrajesh** [comment]
Thank you, closing now.
