### ISSUE TITLE
Incorrect number of images/media displayed in activity feed

### ISSUE THREAD

**Issue by jazzsequence** [buddydev/mediapress#16]
![image](https://cloud.githubusercontent.com/assets/991511/6754688/b764661c-cee3-11e4-8702-fb7cadd8cfb1.png)

This appears to be coming from this line: https://github.com/buddydev/mediapress/blob/master/core/activity/template.php#L152

...except that when I var_dump `$media_ids` I get an empty array, so the count is always 0.

**Comment by jazzsequence** [comment]
...which is really weird because this returns an array of IDs:

`var_dump(mpp_activity_get_attached_media_ids($activity->id));`

**Comment by jazzsequence** [comment]
This line appears to be the issue:

https://github.com/buddydev/mediapress/blob/master/core/activity/template.php#L165

`apply_filters` is being run twice. PR forthcoming.

**Comment by sbrajesh** [comment]
Hi Chris, 
Please give me an hour . I am looking into it.
Most probably it is caused by
mpp_activity_get_attached_media_ids()

**Comment by jazzsequence** [comment]
PR #17

**Comment by sbrajesh** [comment]
Hi,
The problem is if we remove that filter, It will not change the action for the upload to groups as you can see here.
https://github.com/buddydev/mediapress/blob/master/modules/groups/hooks.php#L69

**Comment by sbrajesh** [comment]
Finally found the issue.
On line 153 , we are popping the media ids array to fetch one of the media
https://github.com/buddydev/mediapress/blob/master/core/activity/template.php#L153

and this is causing the actual count to decrease by 1.

**Comment by jazzsequence** [comment]
That makes sense. I will look for the update. I'm not familiar with `array_pop` so I didn't pay much attention to it. :)

**Comment by sbrajesh** [comment]
Fixed in  8569e247e547ddf

**Comment by jazzsequence** [comment]
:+1: This looks good, too.

**Comment by sbrajesh** [comment]
Thank you :)
