### ISSUE TITLE
Multsite Wordpress-Buddypress members cannot upload photo - they get error message

### ISSUE THREAD

**Issue by rhisss** [buddydev/mediapress#18]
Multsite Wordpress-Buddypress members cannot upload photo - they get error message
" xxx.jpg(28 kb)x This file type is not allowed in current gallery. Only files are allowed!"
Multsite Wordpress-Buddypress members - by this I mean - members who can both register and create site. Other photo/gallery like rtmedia, buddypics etc have NO such problem in exactly similar set-up

Individually activating or network-activating - all gives same error as above.

Note : If members can only register but not create individual blog/site, they can upload photos by mediapress. No problems.

Can you please correct this or suggest some work-around ? Is the dev work not happening now? Thanks.

**Comment by pilumati** [comment]
I am also having same problem.

**Comment by sbrajesh** [comment]
@rhisss ,
I will have an update by the coming Tuesday. My apologies for the inconvenience.

**Comment by rhisss** [comment]
Is the update coming?

**Comment by sbrajesh** [comment]
Have you seen recent changelog before asking if the project is dead or not? 
Here is a link https://github.com/buddydev/mediapress/commits/master

For last 1 week, I have been dedicating on this project and we will get stable version by the end of this week. 

Currently, the priority is not multisite network active mode. It will take me some time to test on that(specific to your requirement). Please wait till Friday and i will have some good news for you too.

**Comment by sbrajesh** [comment]
If you have got some time, Please do check the latest update.

**Comment by sbrajesh** [comment]
Closing this ticket as It has been more than a month since last update and I did not receive any feedback here. Also no such error reported by any new members.

Please feel free to reopen if the issue still demonstrates.
