### ISSUE TITLE
uploading not working

### ISSUE THREAD

**Issue by UnbanTwin** [buddydev/mediapress#20]
so when my users upload photos/videos it comes up in the update but then when they post its not there please help

**Comment by sbrajesh** [comment]
@wizardsambolton I am sorry about the trouble. which theme are you using? It could be related to the theme, just need some idea.

**Comment by UnbanTwin** [comment]
@sbrajesh I am using dw-minion

**Comment by sbrajesh** [comment]
checking it now. Please give me 5 mins

**Comment by UnbanTwin** [comment]
ok

**Comment by sbrajesh** [comment]
![mpp-working-on-activity](https://cloud.githubusercontent.com/assets/520939/7659939/80ab1e7a-fb63-11e4-82d3-88d362640472.png)
Please see the image. It is working for me as admin as well as normal user.

Is there any other plugin that might be updating cookies as the uploaded media ids are stored in cookies and attached to the activity when an activity is posted or removed if a new page is loaded

**Comment by geonom** [comment]
I am having the same issue, as admin and as normal user, I can upload a pic and it shows in the preview, but in the final page its not visible at all (the activity shows up, but no image visible). Music files work strangely enough.
Tested also with twentyfourteen and twentyfifteen without any plugins except buddypress, bbpress and mediapress, still the same issue.
If you want to have a look at my test site, I'd be happy to give you an admin account :)

**Comment by sbrajesh** [comment]
Hi,
I am sorry for the trouble. Please provide me access to your site and I can check it in better way.

Thank you
Brajesh

**Comment by geonom** [comment]
Thanks for the offer, sent you a message via your websites contact form with details!

**Comment by sbrajesh** [comment]
Just closing it.
For future, If you see this, please make sure that the status 'public is active. currently, wall galleries must be public.
