### ISSUE TITLE
Delete gallery from user's end

### ISSUE THREAD

**Issue by imagecrisis** [buddydev/mediapress#25]
Hi, great plugin but I'm seeing an issue where a gallery when deleted isn't removed. "Yes, I understand and I want to delete!" is clicked but nothing further happens.

Galleries can be deleted and binned from the WP administration area only.

**Comment by sbrajesh** [comment]
Hi,
Thank you for reporting. It is very strange but might have been a side effect of our recent updates. Please allow me to check it today and get back to you.

Thank you
Brajesh

**Comment by sbrajesh** [comment]
Just checked with the latest version and I was able to delete the galleries. can you please upgrade to latest version and check again?

if it is still happening, please do let me know which version of WordPress/BuddyPress you are using and if it is a multisite installation?

**Comment by imagecrisis** [comment]
Hi, thanks for the reply. I'm using: Buddypress Version 2.3.2.1, WordPress 4.1.1 and latest version of MediaPress. This isn't a multisite install.

A side related issue is that now the quota says 0% used but files can't be uploaded. I get this error: "Unable to upload. You have used the allowed storage quota!"

Not sure if that's related?!

**Comment by sbrajesh** [comment]
That upload issue sounds strange. Can you please mail me access to the site. Please drop me the details via contact form here http://buddydev.com/contact/ 

That will help me to check and assist you.

**Comment by klase** [comment]
I have the same problem. Can only delete galleries from wp-admin

**Comment by sbrajesh** [comment]
Hi @klase ,
I am sorry for the inconvenience. It seems very strange. Can you please open a topic at BuddyDev forum and provide the debug log( You can access debug log by visiting Dashboard->MediaPress-> Tools section)

Thank you
Brajesh

**Comment by sbrajesh** [comment]
Closing it as things have changed a lot in last few months. Please feel free to reopen or use BuddyDev forums if  you have this issue.
