### ISSUE TITLE
PHP7

### ISSUE THREAD

**Issue by markc** [buddydev/mediapress#31]
This is a thread to track usage under PHP7. This error may be related to PHP7.

![snapshot79](https://cloud.githubusercontent.com/assets/8134/11968719/076f2924-a95b-11e5-806e-4de0c5a869b8.jpg)

**Comment by sbrajesh** [comment]
Thank you. It was due to the uniform syntax changes introduced in php7. Fixed here
https://github.com/buddydev/mediapress/commit/2f84811d0e43878e95cabaf6113d5334e00aa6aa

**Comment by sbrajesh** [comment]
Closing it as it has been more than 2 weeks without any reply. Please feel free to reopen if the issue persists.
