### ISSUE TITLE
Mediapress breaks the cropping function of Buddypress

### ISSUE THREAD

**Issue by kylven** [buddydev/mediapress#34]
I've tested this with a few different themes and everytime Mediapress is activated the cropping pane for buddypress profile and group avatars disappears.  Clicking crop image just bumps you to the top of the page.  If I disable mediapress, the upload and cropping function of avatars works fine.

**Comment by sbrajesh** [comment]
Hi,
Have replied to your forum post here.
http://buddydev.com/support/forums/topic/mediapress-breaks-the-cropping-function-of-buddypress/
Closing it in favor of forum discussion.
