### ISSUE TITLE
How to show multiple photos in a grid  in the activity stream 

### ISSUE THREAD

**Issue by rhisss** [buddydev/mediapress#36]
How to show multiple photos in a grid (suppose a grid of 5 or 6 or similar) in the activity stream when multiple photos are uploaded simultaneously. An user uploading say 12 or 15 photos will easily "spam" the stream at the current settings.

**Comment by sbrajesh** [comment]
Thank you for noting it. For now, Please copy "mediapress/templates/mediapress/default/buddypress/activity/views/grid-photo.php" to "yourtheme/mediapress/default/buddypress/activity/views/grid-photo.php" and change this line

`
$mppq = new MPP_Cached_Media_Query( array( 'in' => mpp_activity_get_attached_media_ids( $activity_id ) ) );
`
to
`
$mppq = new MPP_Cached_Media_Query( array( 'in' => array_slice( mpp_activity_get_attached_media_ids( $activity_id ), 0, 5) ) );
`

That will list only upto 5 photos for now. I am also adding an option to do the same from the BuddyPress settings tab from MediaPress settings.
Thank you
Brajesh

**Comment by sbrajesh** [comment]
HI,
I have added the settings and a default limit in
4d0273a5b1327b4ad012035531f2b7be7f8fed78

Marking it as resolved.
