### ISSUE TITLE
Lightbox behavior is not uniform

### ISSUE THREAD

**Issue by rhisss** [buddydev/mediapress#38]
Image thumbnail, when its "added new photo" notification in the stream
opens in lightbox.
When its comment notification in the stream does not open in light box.
![untitled](https://cloud.githubusercontent.com/assets/3778500/13618330/905b5dfe-e5a9-11e5-946f-d8b0d03a7f9f.PNG)

**Comment by sbrajesh** [comment]
Thank you.
Agreed, yes, It is bad experience. I am working on a fix and will have an update soon.

**Comment by rhisss** [comment]
Thanks. This is however a minor issue. Having the option to disable comment activity will solve this problem.

**Comment by sbrajesh** [comment]
sure. I am going to take on the other related ticket first.

**Comment by sbrajesh** [comment]
Marking as resolved since we included it in one of the earlier versions.
