### ISSUE TITLE
in the scenario below, end-users always get error message and cannot upload images even if they have individually saved the settings

### ISSUE THREAD

**Issue by rhisss** [buddydev/mediapress#4]
<b>At present, testing with the latest Mediapress beta, in the  scenario below, end-users always get error message and cannot upload images even if they have individually saved the settings</b>

Install WP 4.1 and install BP 2.1.1 - fresh installs, nothing else
Enable WP multisite - define('MULTISITE', true); define('SUBDOMAIN_INSTALL', false); etc etc
Enable Mediapress, SAVE settings - all checked, Saved
Go to wp-admin/network/site-new.php and create a new site - a new user is created automatically by wordpress if   email address was not in the database
Now edit end-user password etc ( and send email to him with password etc)
Login as that end-user and try to create gallery, upload an image
You can create gallery as an end-user but when you try to upload image
You will get an error-message "xyz.jpg(xyz kb) x This file type is not allowed in current gallery. Only files are allowed!"
<i>This error message and failure to upload happens even if the   end-user has  visited wordpress/end-user-site/wp-admin/edit.php?post_type=mpp-gallery&page=mpp-settings and checked "Enabled Media/gallery types" etc</i>

**Comment by sbrajesh** [comment]
Hi,
Are you able to upload a file from the Media management or post page from the current install. Most probably, It seems a permission issue with the file system. Can you please check if you are able to upload files via wp admin?

**Comment by rhisss** [comment]
For Mediapress files : As an end-user : NO. As site super admin : Yes, from the main site only but not from the sample end-user site. I am testing on localhost and you can easily reproduce the result by following the above steps. In comparison RTmedia or buddypics (github version) has no such problem.

"Can you please check if you are able to upload files via wp admin?" - WP core default Media lets upload files in any scenario, as an end-user or as admin - no problem.

**Comment by sbrajesh** [comment]
I am sorry, I just looked again at your first message. Do you mean that the MediaPress  is network activated?

**Comment by rhisss** [comment]
Yes MediaPress is network activated. If it is not, then individual end-users in the above setup [WP 4.1 + BP 2.1.1 + WP Multisite enabled (('MULTISITE', true); ('SUBDOMAIN_INSTALL', false);)] will not be able to see Mediapress in their accounts

**Comment by sbrajesh** [comment]
It is fixed in the current release.
Just a note though, all the different sites act as a different social network for the MediaPress. So, the photos uploaded on one sub site won't be visible on the other.

We still need to work a lot to make MediaPress truely multisite compatible in network activation mode.

As far as your interpretation of end user is, that is not correct. Those users are admins of sub site. End users are your subscribers who can have control over the admin settings.
