### ISSUE TITLE
Uploading Media from Acivity Directory doesn't create a new activity item

### ISSUE THREAD

**Issue by abegit** [buddydev/mediapress#41]
- When you "Add Media" from a Gallery Page it **DOES** create an activity item, but there's no description.
- When you upload an image from the "Activity Form" it does add it to the gallery, but it **DOES NOT** create a new activity item.
- Pressing "Post Update" only uploads the words inside the textarea as an activity item, **skipping** attaching the currently uploaded image to the activity status.

**_GAMEPLAN:_**
You can add shortcode support for activity statuses
`function oi_add_shortcodes_to_activity_stream() {
        add_filter( 'bp_get_activity_content_body', 'do_shortcode', 1 );
}
add_action('bp_init', 'oi_add_shortcodes_to_activity_stream');`

Going to code a way to automatically add
- `[mpp-media id=XXX]` or
- `[mpp-list-media id=XXX]`

into the current activity item so that when you DO press 'Post Update' it also includes a shortcode to the just uploaded media.

Also it might be possible to implement a repost / reblog feature using this method? The same way Default Buddypress allows to @ people by clicking on a button on their profile page.

Is this a good way to approach it?

**Comment by abegit** [comment]
Also unaware about how commenting caveats

**Comment by sbrajesh** [comment]
HI,
Thank you for posting.
1. There is no shortcode required for the purpose. Did you post the activity after uploading media. The media act as attachment of the activity.

For Repost/Reblog I suggest looking at BuddyPress reshare by imath.

If the activity attachment is not working, it might be a conflict with the theme. It will help us to assit you better if you post on BuddyDev forums.

Thank you
Brajesh

**Comment by abegit** [comment]
Ok, started a thread on BuddyDev.com
