### ISSUE TITLE
Gallery/Image Uploader not showing FrontEnd

### ISSUE THREAD

**Issue by neilgee** [buddydev/mediapress#42]
Having an issue in some themes when Gallery Image Uploader is not showing on the front end when clicking on **view** or **upload**.

For example using Genesis framework will replicate this issue but most Genesis Child Themes are ok, I am trying to find out why the issue occurs if just using the framework.

Attached are 2 screen grabs one showing the gallery and the other showing what happens when **upload** is selected - both grabs also have all the page hooks displaying - it is also odd that the hooks stop being rendered to the page at a certain point near the gallery uploader when the issue occurs.

No other plugins running, no JS errors in console and no PHP errors in debug.

![screen shot 2016-11-24 at 3 05 13 pm](https://cloud.githubusercontent.com/assets/2056045/20586390/8ffa7018-b257-11e6-8425-4f30d326759c.png)

![screen shot 2016-11-24 at 3 05 26 pm](https://cloud.githubusercontent.com/assets/2056045/20586389/8fe870ca-b257-11e6-8165-520f190bc8db.png)

**Comment by sbrajesh** [comment]
Hi Neil,
I am sorry but I am not familiar with Genesis and I may not be of much help. If you find something, Please do let me know. If there is some change needed in MediaPress, please let me know and I will be happy to incorporate.

Thank you.

**Comment by neilgee** [comment]
Through trial and error eventually worked it down to a key/value pair in a Genesis Update Settings array...

```
add_action( 'after_switch_theme', 'rx_theme_setting_defaults' );
/**
 * Theme Setup After switching themes.
 */
function rx_theme_setting_defaults() {

	if ( function_exists( 'genesis_update_settings' ) ) {

		genesis_update_settings( array(
			'blog_cat_num'              => 5,
 			//'content_archive'           => 'excerpts',
			'content_archive_limit'     => 0,
			'content_archive_thumbnail' => 1,
			'posts_nav'                 => 'numeric',
			'site_layout'               => 'full-width-content',
		) );

	}
	update_option( 'posts_per_page', 5 );

}
```
As bizarre as it sounds, by removing `'content_archive'    => 'excerpts',` from the array and switching between 2 themes the media functionality starts working  - FWIW the same issue occurs by using the other BuddyPress media plugin rtMedia

This will basically occur in any Genesis theme if the default theme setting for **Content Archives** is set to `Entry Excerpts`
![screen shot 2016-11-26 at 12 57 01 pm](https://cloud.githubusercontent.com/assets/2056045/20637306/13f36fb0-b3d8-11e6-9076-07b9e9157a9a.png)
