### ISSUE TITLE
MediaPress Gravity Forms Server Error 500

### ISSUE THREAD

**Issue by neilgee** [buddydev/mediapress#43]
I have found if MediaPress is enabled and Gravity Forms with the User Registration Add on and User Activation is checked as below.

![screen shot 2016-11-29 at 11 44 18 am](https://cloud.githubusercontent.com/assets/2056045/20692031/6b598a52-b629-11e6-9c20-7e850f036ed8.png)

The form will not post and a server 500 error occurs - if MediaPress is disabled the form posts successfully.

Here is some output from debug log...
```
[29-Nov-2016 00:50:48 UTC] PHP Fatal error:  Cannot redeclare get_dirsize() (previously declared in /home/roomxchange/public_html/wp-content/plugins/mediapress/core/storage/class-mpp-local-storage.php:922) in /home/roomxchange/public_html/wp-includes/ms-functions.php on line 1690
```

**Comment by sbrajesh** [comment]
Hi Neil, are you on a multisite install?

**Comment by neilgee** [comment]
No,  standalone

**Comment by sbrajesh** [comment]
Then it is a bug with Gravity form addon. They should not have included ms-functions.php. It is only loaded on multisite installs by default, and the function conflicting,  is something that we provide as an abstraction on the non multisite install.

Please inform the Gravity form addon developer about the issue.

**Comment by neilgee** [comment]
Ok opened a support ticket with GF - see what they say...

**Comment by sbrajesh** [comment]
Sure. Please do let me know. Most probably they will update the code and conditionally add any abstraction function they need.

**Comment by neilgee** [comment]
Heard back from GF, they will look to sort this - but no eta - 

>  it will take a few months or maybe even longer.

Which is good - but unfortunately I was looking forward to using MediaPress on this project but I need GF useraddon.

**Comment by sbrajesh** [comment]
Hi Neil,
You can remove the following two functions manually
get_dirsize
recurse_dirsize

https://github.com/buddydev/mediapress/blob/master/core/storage/class-mpp-local-storage.php#L909

for now. Please do check if it causes any issue on upload? If yes, them you may need to add the function at lower priority( say include a file with these functions on init action).
Hope that helps.

**Comment by neilgee** [comment]
Ok great will try that out

**Comment by studioleland** [comment]
Adding to this.  I have all the same activated except: WP email disabled and user activation is automatic.  Not sure if that helps.  Will try GF fix.

**Comment by sbrajesh** [comment]
HI Leland,
I have put a fix for it in the plugin now.
Since we were only overriding 2 small functions from the ms, I moved it to private scope.
https://github.com/buddydev/mediapress/commit/6221d81afc7031f932bac2c8bba7bad35b05b2c6

That fixes it. Will be available in next release.
