### ISSUE TITLE
Slow query on mpp_get_object_ids, mpp_get_object_count and mpp_get_adjacent_object_id

### ISSUE THREAD

**Issue by regisvidal** [buddydev/mediapress#44]
I have a database with more than 5000 galleries and calling theses functions is very slow (more than 10 seconds) due to IN in the query.
the query for mpp_get_object_count is:
```
SELECT COUNT( DISTINCT p.ID ) AS total
FROM wp_posts AS p
INNER JOIN wp_postmeta AS pm ON p.ID = pm.post_id
WHERE p.post_type = 'mpp-gallery'
AND p.post_status = 'publish'
AND pm.meta_key = '_mpp_component_id'
AND pm.meta_value =1
AND ID
IN (

SELECT DISTINCT t.object_id
FROM (

SELECT DISTINCT tr.object_id AS object_id
FROM wp_term_relationships AS tr
WHERE tr.term_taxonomy_id
IN (
'29'
)
UNION ALL SELECT DISTINCT tr.object_id AS object_id
FROM wp_term_relationships AS tr
WHERE tr.term_taxonomy_id
IN (
'31', '32', '35'
)
UNION ALL SELECT DISTINCT tr.object_id AS object_id
FROM wp_term_relationships AS tr
WHERE tr.term_taxonomy_id
IN (
'38'
)
) AS t
GROUP BY object_id
HAVING count( * ) >=3
)
```

it much more faster to convert the IN clauses to INNER JOIN clauses:

```
SELECT COUNT( DISTINCT p.ID ) AS total
FROM (
  SELECT DISTINCT t.object_id as inid
  FROM (

  SELECT DISTINCT tr.object_id AS object_id
  FROM wp_term_relationships AS tr
  WHERE tr.term_taxonomy_id
  IN (
  '29'
  )
  UNION ALL SELECT DISTINCT tr.object_id AS object_id
  FROM wp_term_relationships AS tr
  WHERE tr.term_taxonomy_id
  IN (
  '31', '32', '35'
  )
  UNION ALL SELECT DISTINCT tr.object_id AS object_id
  FROM wp_term_relationships AS tr
  WHERE tr.term_taxonomy_id
  IN (
  '38'
  )
  ) AS t
  GROUP BY object_id
  HAVING count( * ) >=3
) a
JOIN wp_posts AS p ON a.inid = p.ID
INNER JOIN wp_postmeta AS pm ON p.ID = pm.post_id
WHERE p.post_type = 'mpp-gallery'
AND p.post_status = 'publish'
AND pm.meta_key = '_mpp_component_id'
AND pm.meta_value =1
```

**Comment by sbrajesh** [comment]
Hi,
I am sorry, I did not see it.Thank you for the suggestion. It is better for sure.
Still, for 5000 galleries, that time is unexpected unless you have a huge meta table(how many entries/size do you see for the post meta table). On one of installs I checked a 3rd party plugin had 5.5 million entries with 2.9GB meta table(they were using visual composer). These factors too contribute to the query performance.

To be honest, We are planning to migrate from the meta_key and terms to another flat table for far better performance in future and avoid getting penalty due slower meta queries on larger installs.

Thank you

**Comment by sbrajesh** [comment]
I have added caching support for gallery count now bf65c059e3019fb616d7e4cff4be841e740e3f5e. It should improve the performance.
