### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ThatDamnCreature** [buddydev/mediapress#48]
Fatal error: Call to a member function activity_display() on boolean in /home/user_dir/public_html/folder_name/wp-content/plugins/mediapress/modules/buddypress/activity/mpp-activity-hooks.php on line 92

I can't seem to beat this one.. any sggestions?

**Comment by sbrajesh** [comment]
Please visit Dashboard->MediaPress->Settings->BuddyPress and check if the view type for activity is specified there or not?

Also, Is there any chance that you are using custom view for activity?

**Comment by ThatDamnCreature** [comment]
I'm not using a custom view and  by view type for activity you mean which field? I have no view type option

**Comment by sbrajesh** [comment]
Thank you for clarifying. 
Can you please check for the activity view. It can be seen under the BuddyPress tab in MediaPress settings.

Please see the image.
![activity-view](https://cloud.githubusercontent.com/assets/520939/24694815/0c049448-1a01-11e7-8318-cd4b513294bb.png)

**Comment by ThatDamnCreature** [comment]
I'm mirroring those exact settings yes.

**Comment by sbrajesh** [comment]
It seems that there is a media which does not have type set.

Will it be feasible for you to grant me temporary dashboard access to check Gallery and media? Also, I am pushing one update to avoid any fatal in future.

**Comment by ThatDamnCreature** [comment]
Of course
http://crossfitnorthport.net/membersbox/ 
--password removed.

**Comment by sbrajesh** [comment]
Thank you.

**Comment by sbrajesh** [comment]
can you please recheck that link is not opening for me.

**Comment by ThatDamnCreature** [comment]
http://crossfitnorthport.net/membersbox/

**Comment by sbrajesh** [comment]
I am sorry but it is giving me
ERR_CONNECTION_TIMED_OUT

Do you have any restriction on accessing from locations? I am trying to access it from India.

**Comment by ThatDamnCreature** [comment]
That's quite possible at the server lvl

**Comment by ThatDamnCreature** [comment]
I appreciate you trying to help. I just exhausted everything I knew to do minus disabling the plugin. It's such an odd error because I only get it on the master activity feed.

**Comment by sbrajesh** [comment]
Hi,
Please allow me to push an update in the evening. There is one situation where this error is possible when the type for media is not set. It is still a bad thing to give fatal. I will update and post back.

Thank you
Brajesh

**Comment by ThatDamnCreature** [comment]
Thank you, Brajesh. I'll keep an eye out for it.

**Comment by sbrajesh** [comment]
Thank you too for the patience Ben.
Will do post back later today.

**Comment by sbrajesh** [comment]
I am not sure if we got it resolved on our forum or not. Closing it due to the age. Please feel free to use https://buddydev.com/support/forums/ for any future support.
