### ISSUE TITLE
output classes to body for different views

### ISSUE THREAD

**Issue by mourique** [buddydev/mediapress#5]
Hey,

first off, sbrajesh, nice plugin. It works well so far. There are some things here and there, but i hope i can contribute soon.

i am customizing all mediapress templates from inside my theme and it would be great for styling if we had more finer grained body classes. 

currently it only show »mediapress«

<body class="bp-user my-account mediapress party buddypress page page-id-5 page-template-default logged-in js" id="__mpp-uploader-id-0">

but better would be »mediapress single-gallery-view« or »mediapress single-media-view«

Maybe you can point me in the direction, i would make a PR.

cheers,
Felix

**Comment by sbrajesh** [comment]
Hi Felix,
Thank you. I am happy that you are finding it useful.

Thank you for bringing the body class point. I am sure It is useful and I will commit it tonight to the main repo. In the meantime, you can filter on 'body_class' and use the functions 
mpp_is_single_media() and mpp_is_single_gallery() to add these classes.

hope that helps.

**Comment by mourique** [comment]
Hi! Thanks for the heads up!

**Comment by mourique** [comment]
Hey Brajesh,

is there a function to see if current page is an edit or management screen? mpp_is_gallery_management() does not seem to work for filtering on body_class.

cheers,
Felix

**Comment by sbrajesh** [comment]
Hi Felix,
I have updated MediaPress in 2932af9a38a32e1 to add unique classes on each page. Please do take a look at this.

https://github.com/buddydev/mediapress/commit/2932af9a38a32e12173f43abd1a2ff1a96127029#diff-3

The general structure of classes are like this

mpp-page  -> All MediaPress pages
mpp-page mpp-page-directory -> If we are on the gallery directory page

mpp-page  mpp-page-member -> all member gallery page
mpp-page mpp-page-groups -> all group gallery pages
mpp-page mpp-page-{component_name} this is the format we use(as you see that I replaced it with members|groups above)

Now, for Individual gallery etc. It will write the example for members component, you will need to replace members with groups to get the same for groups

mpp-page mpp-page-members mpp-page-gallery-list mpp-page-gallery-list-members -> MediaPress landing page( or gallery listing page for single member)

mpp-page mpp-page-members mpp-page-single-gallery mpp-page-single-gallery-photo mpp-page-single-gallery-loggedin -> For single gallery with type='photo' and status ='loggedin'
The format for single gallery is like:-

mpp-page mpp-page-members mpp-page-single-gallery mpp-page-single-gallery-{type} mpp-page-single-gallery-{status} where type can be photo|audio|video|docs etc( any registered and valid type ) and status = public|private|loggedin|friendsonly etc.

For single media
mpp-page mpp-page-members mpp-page-media-single mpp-page-media-single-photo

The format is:-
mpp-page mpp-page-members mpp-page-media-single mpp-page-media-single-{type}

For the manage media the format is

mpp-page mpp-page-members mpp-page-media-management mpp-page-media-management-{type} mpp-page-media-manage-action-{edit-action}
An example is:-
mpp-page mpp-page-members mpp-page-media-management mpp-page-media-management-photo mpp-page-media-manage-action-edit

 And for manage gallery, It is like:-
mpp-page mpp-page-members mpp-page-gallery-management mpp-page-gallery-management-{type} mpp-page-gallery-manage-action-{edit-action}

An example is
mpp-page mpp-page-members mpp-page-gallery-management mpp-page-gallery-management-photo mpp-page-gallery-manage-action-edit

Hope that helps.

**Comment by sbrajesh** [comment]
closing this ticket as we have it in the plugin now.
