### ISSUE TITLE
PHP files support

### ISSUE THREAD

**Issue by filiptronicek** [buddydev/mediapress#51]
Can you please provide a checkbox for people to allow PHP file uploads? I know it is for security reasons, but can you still make it (maybe even looking for some bad stuff in the file itself)? 
I have a code-sharing file [http://codify.maweb.eu/](http://codify.maweb.eu/). Thank you, regards Filip.

**Comment by sbrajesh** [comment]
My apologies for overlooking it.
I am sorry but we won't be able to have it.
